// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3o-cPWWjfzLXfWr_6E-J6J_qA-hyT0TI',
    appId: '1:195202631708:web:9c758a5ae889b3ff4bb7d9',
    messagingSenderId: '195202631708',
    projectId: 'app-abastecimento-davy',
    authDomain: 'app-abastecimento-davy.firebaseapp.com',
    storageBucket: 'app-abastecimento-davy.firebasestorage.app',
    measurementId: 'G-BS5HHZM15Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLIcAxVOpvHdIOaVQrgEeHjlLJKbkEaas',
    appId: '1:195202631708:android:3a2eb44cf88582564bb7d9',
    messagingSenderId: '195202631708',
    projectId: 'app-abastecimento-davy',
    storageBucket: 'app-abastecimento-davy.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3o-cPWWjfzLXfWr_6E-J6J_qA-hyT0TI',
    appId: '1:195202631708:web:679a672b0de8bd8c4bb7d9',
    messagingSenderId: '195202631708',
    projectId: 'app-abastecimento-davy',
    authDomain: 'app-abastecimento-davy.firebaseapp.com',
    storageBucket: 'app-abastecimento-davy.firebasestorage.app',
    measurementId: 'G-KSRJPQV2J0',
  );
}
